services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "thepass123"
      POSTGRES_DB: "postgres"
  minio:
    container_name: minio
    image: 'bitnami/minio:latest'
    volumes:
      - 'minio_data:/data'
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_USE_SSL: "0"
      MINIO_DEFAULT_BUCKETS: "storage-dev"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 3
volumes:
  minio_data: