app:
  env: local
  logLevel: debug
  outputFile: logs/stdout.log
  healthHost: 127.0.0.1
  healthPost: 8080
s3:
  host: 127.0.0.1
  port: 9000
  accessKey: pwb1OknjOtg3HxhIxwOI
  bucket: storage-dev
  secretAccess: 2HjWjtpoPaYs0jrXhvYgJlVzhN0F3WyuTI6WXRsS
postgresql:
  host: 127.0.0.1
  port: 5442
  user: postgres
  password: thepass123
  database: postgres
  maxOpenConn: 10
  maxIdleConn: 10
  duration: 5s
  migrationFolder: ./migrations
security:
  tokenTTL: 1h
  signKey: 87ccd01b-0b99-4f3a-8422-dd088f22cde0
  certPath: ./certs/cert.pem
  certKeyPath: ./certs/key
server:
  host: 127.0.0.1
  port: 9090
  timeout: 30s